version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"
